Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen.Models
{
    public class Cliente
    {
        public int id { get; set; }
        public string? name { get; set; }
        public string? latitud { get; set; }
        public string? longitud { get; set; } 
        public string? fechaInicio { get; set; } 
        public string? horaInicio { get; set; } 
        public string? fechaFin { get; set; } 
        public string? horaFin { get; set; } 
        public string? estatus { get; set; } 

    }
}

Models/ErrorViewModel.cs
namespace Examen.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Orden.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen.Models
{
    public class Orden
    {
        public int ordenesPendientes { get; set; } 
        public int ordenesAtendidas { get; set; } 
        public int ordenenesCanceladas { get; set; } 
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Examen.Models;

namespace Examen.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/SocketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Examen.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace Examen.Controllers
{
    public class SocketsController : Controller
    {

        private readonly IHubContext<MensajesHub> hubContext;
        public SocketsController(IHubContext<MensajesHub> hubContext){
            this.hubContext = hubContext;
        }
        public IActionResult Home(){
            return View();
        }

        public IActionResult Form(){
            return View();
        }

        public IActionResult Dashboard(){
            return View();
        }

        public IActionResult Logistics(){
            return View();
        }
    }
}

Controllers/TransaccionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Examen.Models;
using Examen.Services;
using Microsoft.AspNetCore.Mvc;

namespace Examen.Controllers
{
    public class TransaccionesController : Controller
    {
        private readonly ITransacciones db;

        public TransaccionesController(ITransacciones db)
        {
            this.db = db;
        }

        [HttpGet]
        public IActionResult GetClientes()
        {
            return Json(db.ConsultarClientes());
        }

        [HttpGet]
        public IActionResult GetCliente(int id)
        {
            return Json(db.ConsultarCliente(id));
        }

        // [HttpPost]
        // public IActionResult AddCliente([FromBody] Cliente c)
        // {
        //     db.Agregar(c);
        //     return Json(new { Mensaje = "Insertado correctamente" });
        // }

        [HttpPost]
        public IActionResult AddCliente([FromBody] Cliente c)
        {
            var estatusPermitidos = new List<string> { "Pendiente", "Atendida", "Cancelada" };
            if (string.IsNullOrEmpty(c.estatus) || !estatusPermitidos.Contains(c.estatus))
            {
                return Json(new { Mensaje = "Estatus inválido. Debe ser 'Pendiente', 'Atendida' o 'Cancelada'" });
            }

            db.Agregar(c); 
            return Json(new { Mensaje = "Insertado correctamente" });
        }



        [HttpPost]
        public IActionResult UpdateCliente([FromBody] Cliente c)
        {
            int result = db.ActualizarCliente(c);
            if (result == -1)
            {
                return Json(new { Mensaje = "No se pudo actualizar" });
            }
            return Json(new { Mensaje = "Actualizado correctamente" });
        }

        [HttpDelete]
        public IActionResult DeleteCliente(int id)
        {
            bool eliminar = db.EliminarCliente(id);
            if (eliminar)
            {
                return Json(new { Mensaje = "Eliminado" });
            }
            return Json(new { Mensaje = "No se encontró" });
        }


        [HttpGet]
        public IActionResult GetClientesPorEstatus(string estatus)
        {
            var clientes = db.ConsultarClientes(); // Obtener todos los clientes
            var clientesFiltrados = clientes.Where(c => c.estatus == estatus).ToList(); // Filtrar por estatus
            if (clientesFiltrados.Count == 0)
            {
                return Json(new { Mensaje = "No se encontraron clientes con ese estatus" });
            }
            return Json(clientesFiltrados);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Examen.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Telefonia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sockets" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sockets" asp-action="Logistics">Logistica</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sockets" asp-action="Dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sockets" asp-action="Form">Formulario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Examen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Sockets/Dashboard.cshtml
<h1>Grafica</h1>
<div id="chart">
    <canvas id="myChart"></canvas>
</div>

<div id="map">
</div>



<button id="btn">Solucionar</button>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="~/js/dashboard.js"></script>
<script src="~/js/form.js"></script>

Views/Sockets/Form.cshtml
<h3>Ejemplo de Geolocalizacion</h3>
<p id="lugar"></p>

<label for="nombre">Ingresa nombre</label>
<input type="text" id="txtName" placeholder="Nombre"></input>
<br>

<div id="map">
</div>

<button type="button" id="btnEnviar">Enviar</button>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

<script src="~/js/signalr.js"></script>
<script src="~/js/form.js"></script>

Views/Sockets/Home.cshtml
<div class="container" id="contenedor">
    <table id="tabla" class="table table-striped table-bordered mt-4">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Cliente</th>
                <th scope="col">Fecha envió</th>
                <th scope="col">Hora envió</th>
                <th scope="col">Fecha respuesta</th>
                <th scope="col">Hora respuesta</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<script src="~/js/signalr.js"></script>
<script src="~/js/home.js"></script>

Views/Sockets/Logistics.cshtml
<div id="map"></div>

<div class="container" id="contenedor">
    <table id="tabla" class="table table-striped table-bordered mt-4">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Cliente</th>
                <th scope="col">Fecha envió</th>
                <th scope="col">Hora envió</th>
                <th scope="col">Fecha respuesta</th>
                <th scope="col">Hora respuesta</th>
                <th scope="col">Estatus</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<label for="estatus">Estatus:</label>
  <select name="estatus" id="estatus">
    <option value="atendida">Atendida</option>
    <option value="cancelada">Cancelada</option>
  </select>
<button id="btnActualizar">Actualizar</button>


<script src="~/js/signalr.js"></script>
<script src="~/js/logistics.js"></script>